#! /bin/bash
#
# Java program assumes this is a filter, if you write more, less, or redirect
# to read from stdin you may be ruining it
cat $* |\
/usr/bin/perl -0pe 's|//.*?\n|\n|g; s#/\*(.|\n)*?\*/##g;' |\
sed '/^\s*$/d' |\
sed 's/^\s*//' |\
sed 's/\s*$//' |\
sed 's/\s+/ /' |\
sed 's/\([^a-zA-Z$_]\) \([^a-zA-Z$_]\)/\1\2/g' |\
sed 's/\([^a-zA-Z$_]\) \([a-zA-Z$_]\)/\1\2/g' |\
sed 's/\([a-zA-Z$_]\) \([^a-zA-Z$_]\)/\1\2/g' |\
cat
