#!/bin/bash -f

echo "Java files: " `find . -name *.java | wc -l` 

[ ! -e all_sources.cat ] || rm -f all_sources.cat  
[ ! -e all_sources.cat.gz ] || rm -f all_sources.cat.gz 
find . -name *.java | xargs cat >> all_sources.cat 
echo "Lines: "`wc -l all_sources.cat`
echo "Words: "`wc -w all_sources.cat`
echo "Characters: "`wc -w all_sources.cat`

gzip --force -k all_sources.cat
ls -l all_sources.cat all_sources.cat.gz
S0=`du -b "all_sources.cat" | cut -f1`
S1=`du -b "all_sources.cat.gz" | cut -f1`
echo $S0 $S1
echo "Compressed $S0 bytes into $S1 bytes; ratio = " `echo "scale=3;$S1/$S0"|bc`

[ ! -e all_sources.jack ] || rm -f all_sources.jack  
[ ! -e all_sources.jack.gz ] || rm -f all_sources.jack.gz 
echo "Java files: " `find . -name *.java | wc -l` 
find . -name *.java | xargs ../../Program/jack >> all_sources.jack 
wc all_sources.jack
gzip --force -k all_sources.jack
ls -l all_sources.jack all_sources.jack
S0=`du -b "all_sources.jack" | cut -f1`
S1=`du -b "all_sources.jack.gz" | cut -f1`
echo $S0 $S1
echo "Compressed $S0 bytes into $S1 bytes; ratio = " `echo "scale=3;$S1/$S0"|bc`
